### ISSUE TITLE
no "opencv2/contrib/contrib.hpp" found in opencv3.2

### ISSUE THREAD

**Issue by winer632** [tapasya234/RecognitionAndFrequencyCountOfIndividuals#1]

**Comment by tapasya234** [comment]
That is true. In the default OpenCV 3.2, contrib.hpp and a lot other advanced files are not being released. That is why I used OpenCV 2.4.13 for this application. But if you want to use OpenCV 3.2, it can be done by downloading an extra repository from GitHub and then follow the instructions provided in this link: https://stackoverflow.com/questions/28323077/contrib-module-missing-in-opencv-3-0
Though it is for OpenCV 3.0, the same guidelines can be followed for OpenCV 3.2. Since I already worked on few applications using OpenCV 3.2, I wanted to try OpenCV 2.4.13 and check the differences. So I haven't followed the instructions provided in the link.

**Comment by winer632** [comment]
Thank you!
